sos_seva/informer/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('twitter', views.index, name='twitter_search'),
    path('get_ques', views.get_ques, name='get_ques'),
    path('ticket_dashboard', views.ticket_dashboard, name='ticket_dashboard'),
    # url(r'^info_ret', views.information_ret.as_view(), name='info_ret'),
]

app_name = 'informer'

sos_seva/seva/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls import include
#from message.admin import event_admin_site

admin.site.site_header = "SEVA Admin"
admin.site.site_title = "SEVA Admin Portal"
admin.site.index_title = "Welcome to SEVA Admin Portal"
#admin.site.site_url = "/seva_api/"
urlpatterns = [
    #url(r'^', admin.site.urls),
    path('WhatsAppUsers/', include('message.urls',namespace='message_api')),
    url(r'seva_admin/', admin.site.urls),
    path('', include('signup.urls')),
    # path('isb_db/', include('isb_db.urls', namespace='isb_db')),
    path('search/', include('isb_db.urls', namespace='search')),
    path('informer/', include('informer.urls', namespace='informer')),
    #path('seva_api/seva_admin/', admin.site.urls)
]

#print(urlpatterns)

#print("admin",admin.site.urls)

sos_seva/informer/models.py
from django.db import models

# Create your models here.
class tweet(models.Model):
    text = models.TextField(null = True)
    place = models.TextField(null=True)
    date = models.DateTimeField(null=True)
    label = models.TextField(null = True)
    keyword = models.CharField(null = True, max_length=100)
    class Meta:
        db_table = "tweet_data"

sos_seva/informer/views.py
from django.shortcuts import render, redirect
from datetime import datetime, timedelta

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from .models import tweet
from .tweet_scraper import *
# Create your views here.


def index(request):
    return render(request, 'index.html')


def ticket_dashboard(request):
    return redirect('/seva_admin/message/whatsappusers')


@csrf_exempt
def get_ques(request):
    # TODO: Fix key error, question from template being returned correctly
#    ques = request.POST.get('ques', None)
    if request.method == "POST":
        print("inside post")
        ques = request.POST.get('ques', None)
        end_date = datetime.today()
        start_date = end_date - timedelta(days=2)
        data = tweet.objects.filter(date__range=[start_date, end_date]).values()
        similarity_vals = similarity(ques, data)
        similarity_dict = {"tweet": similarity_vals}
        print(similarity_dict)
        return JsonResponse({'tweets': similarity_vals}, safe=False)
    else:
        print("outside post")
        return JsonResponse({'tweets': "Error"}, safe=False)



#1) Chron job script
#2) Data reading in views.py
#3) Passing the data through similarity funciton
#4) Change in index.html based on the dicitonary created in views.py

sos_seva/informer/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Report</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="">Home</a></li>
                    <li class="breadcrumb-item active">Twitter</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">

            <div class="clearfix hidden-md-up"></div>

        </div>

        <!-- Main row -->

        <div class="row">
            <div class="col-md-12">
                <!-- OPTIONS DROPDOWN -->
                 <div class="card">
                    <div class="card-header border-transparent">
                        <h3 class="card-title">Search</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="search_wrap">
                            <div class="input-group mb-3 form-group has-search">

                                <input type="text" class="form-control" placeholder="Search" id="ques">

                                <div class="input-group-append">
                                    <button class="btn btn-primary search-btn" onclick="getResult()">Search</button>
                                </div>

                            </div>
                        </div>
                    </div>

                 </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>

        <div id="loader">
            <img src="{% static 'images/loading.gif' %}" style="margin-top: 10%; height: 250px;">
        </div>

        <div class="row">
            <div class="col-md-12">
                <!-- TABLE: LATEST ORDERS -->
                 <div class="card">
                    <div class="card-header border-transparent">
                        <h3 class="card-title">Results</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div id="results_area">

                        </div>
                        <!-- /.table-responsive -->
                    </div>

                 </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!--/. container-fluid -->
</section>
<!-- /.content -->


<script>
    var init_flag = false;

    $(document).ready(function () {
        console.log("ready")
    })

    function getResult(){
    var ques = $('#ques').val()
    $('#results_area').html("");
    $.ajax({
        url: "{% url 'informer:get_ques' %}",
        type: 'POST',
        data: {'ques':ques},
        success: function(result){
            console.log(result)
            for (tweet in result['tweets']){
                $('#results_area').append(result['tweets'][tweet]);
                $('#results_area').append("<br>");
            }
        },
            error:function(err){
                alert("Error " + err.statusText);

        }
    });
}


$(document).ajaxStart(function(){
  // Show image container
  $("#loader").show();
});
$(document).ajaxComplete(function(){
  // Hide image container
  $("#loader").hide();
});

</script>


{% endblock %}