sos_seva/seva/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls import include
#from message.admin import event_admin_site

admin.site.site_header = "SEVA Admin"
admin.site.site_title = "SEVA Admin Portal"
admin.site.index_title = "Welcome to SEVA Admin Portal"
#admin.site.site_url = "/seva_api/"
urlpatterns = [
    #url(r'^', admin.site.urls),
    path('WhatsAppUsers/', include('message.urls',namespace='message_api')),
    url(r'seva_admin/', admin.site.urls),
    path('', include('signup.urls')),
    # path('isb_db/', include('isb_db.urls', namespace='isb_db')),
    path('search/', include('isb_db.urls', namespace='search')),
    path('informer/', include('informer.urls', namespace='informer')),
    #path('seva_api/seva_admin/', admin.site.urls)
]

#print(urlpatterns)

#print("admin",admin.site.urls)

sos_seva/signup/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.user_login, name='role_login'),
    path('authenticateUser', views.authenticateUser, name='authenticateUser'),
    path('logout', views.user_logout, name='user_logout'),
    path('register',views.register,name='register'),
    ]

app_name = 'signup'

sos_seva/signup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

# USER_TYPE = [
#     ('stateadmin', 'stateadmin'),
#     ('nodaladmin', 'nodaladmin'),
#     ('hospitaladmin', 'hospitaladmin'),
# ]

COMMUNITY_LIST = [
    ("", ""),
    ('mirinda', 'MIRINDA'),
]

# USER_TYPE = [
#     ('stateadmin', 'stateadmin'),
#     ('nodaladmin', 'nodaladmin'),
#     ('hospitaladmin', 'hospitaladmin'),
# ]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_no = models.CharField(max_length=50, null=True,
                            blank=True, default="")
    community = models.CharField(max_length=50, null=True,
                            blank=True, choices=COMMUNITY_LIST, default="")

    def __str__(self):
        return "{} - {}".format(self.user, self.community)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    # if instance.profile:
    if hasattr(instance, 'profile'):
        instance.profile.save()

sos_seva/signup/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.contrib.auth.models import User,auth



# Create your views here.
@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        request.session['is_logged'] = False
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if not user:
            messages.info(request, 'Invalid Credentials')
            return render(request, "login.html")
        else:
            login(request, user)
            request.session['is_logged'] = True
            request.session['username'] = username
            request.session['first_name'] = request.user.first_name
            request.session['last_name'] = request.user.last_name
            return redirect('isb_db:dashboard')

    else:
        # import pdb;pdb.set_trace()
        if request.user.is_authenticated:
            request.session['is_logged'] = True
            request.session['username'] = request.user.username
            request.session['first_name'] = request.user.first_name
            request.session['last_name'] = request.user.last_name
            return redirect('isb_db:dashboard')
        else:
            return render(request, 'login.html')



@csrf_exempt
def authenticateUser(request):
     return redirect("insect:insect_dashboard")

def user_logout(request):
    logout(request)
    return redirect('signup:role_login')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username already registered')
                return redirect('signup:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email already registered')
                return redirect('signup:register')
            else:
                user = User.objects.create_user(username=username,password=password1,email=email,first_name=first_name)
                user.save();
                messages.info(request,'User created successfully')
                return redirect('signup:role_login')
        else:
            messages.info(request,'Password mismatch')
            return redirect('signup:register')
    else:
        return render(request,'register.html')

sos_seva/signup/templates/forgot-password.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Forgot Password</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>

      <form action="recover-password.html" method="post">
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="login.html">Login</a>
      </p>
      <p class="mb-0">
        <a href="register.html" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>

</body>
</html>

sos_seva/signup/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SOS Seva | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{% static 'images/Logo.ico' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <script src="{% static 'js/authenticate.js' %}"></script>
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <!--a href="#"><img src="{% static 'images/logo.png' %}" alt="Logo" style="width:191px;" alt="Friends of The Farmers"></a-->
  </div>
  <!--div class="login-logo">
    <a href="#"><img src="{% static 'dist/img/kalamitr_logo_blue.png' %}" alt="Logo" style="height: 41px;border-radius: 10px;"><b>Kalamitr</b></a>
  </div-->
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <!--form method="post" id="supplier_login_form" action="{% url 'signup:authenticateUser' %}"-->
       <form method="post" id="supplier_login_form" action="" onsubmit="return function()" name="form">

        <div class="input-group mb-3">

          <input required type="text" class="form-control" placeholder="Username" value="" id="username" name="username">

          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            <input required type="password" class="form-control" placeholder="Password" value="" id="password" name="password">

          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row" style="text-align:center">
          <!-- /.col -->
          <div class="col">
            <button type="submit" class="btn btn-primary btn-block" id="">Sign In</button>

          </div>
          <br><br>
<!--          <div class="container register">-->
<!--            <p>No account? <a href="{% url 'signup:register' %}">Register</a></p>-->
<!--          </div>-->
          <!-- /.col -->
        </div>

        <div class="row" id="message">
          <div class="col">
          {% if messages %}
        {% for message in messages %} &nbsp
        <h6 > {{message}} </h6>
          {% endfor %}
          {% endif %}
          </div>
        </div>


        <div class="row" style="text-align:center;height:10px">
          <!-- /.col -->
          <div class="col">
            <span id="login_message">
              {% if 'login_message' in request.session %}
                {{request.session.login_message}}
              {% endif %}
            </span>
          </div>
          <!-- /.col -->
        </div>
		 <div class="row" style="text-align:center;height:10px">
          <!-- /.col -->
          <div class="col">

            <p>
                Powered by
                <a href="https://www.techmahindra.com/" target="_blank"> Tech Mahindra Limited</a>
            </p>

          </div>
          <!-- /.col -->
        </div>       
      </form>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<script>
  $("#login_message").fadeOut(10000);
</script>
<script>
  function validation()
  {
    var username=document.forms["form"]["username"].value;
    var password=document.forms["form"]["password"].value;
    if(username=="")
    {

        document.getElementById("username")
        return false;
    }
    if(password=="")
    {
        document.getElementById("password")
        return false;
    }
    return true;
  }


</script>


</body>
</html>

sos_seva/signup/templates/recover-password.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Recover Password</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You are only one step a way from your new password, recover your password now.</p>

      <form action="login.html" method="post">
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Confirm Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Change password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="login.html">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>

</body>
</html>

sos_seva/signup/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <script src="{% static 'js/authenticate.js' %}"></script>
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form action="{% url 'signup:register'%}" method="post">
        {% csrf_token%}
        <div class="input-group mb-3">
          <input type="text" name="first_name" class="form-control" placeholder="Full name">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>

          <div class="input-group mb-3">
          <input type="text" name="username" class="form-control" placeholder="Username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>

        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password1" name="password1" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password2" name="password2"class="form-control" placeholder="Retype password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
        </div>
      </form>
      <div>
        {% for message in messages%}
        <h6> {{ message }} </h6>
        {% endfor %}
      </div>

    </div>

  </div>
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>
</html>