sos_seva/isb_db/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    url(r'^info_ret', views.information_ret.as_view(), name='info_ret'),
    url(r'^get_details/$', views.get_details, name='get_details'),
    url(r'^update_info/$', views.update_database, name='update_info'),
    url(r'^new_resource/$', views.new_resource, name='new_resource')
]

app_name = 'isb_db'

sos_seva/seva/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls import include
#from message.admin import event_admin_site

admin.site.site_header = "SEVA Admin"
admin.site.site_title = "SEVA Admin Portal"
admin.site.index_title = "Welcome to SEVA Admin Portal"
#admin.site.site_url = "/seva_api/"
urlpatterns = [
    #url(r'^', admin.site.urls),
    path('WhatsAppUsers/', include('message.urls',namespace='message_api')),
    url(r'seva_admin/', admin.site.urls),
    path('', include('signup.urls')),
    # path('isb_db/', include('isb_db.urls', namespace='isb_db')),
    path('search/', include('isb_db.urls', namespace='search')),
    path('informer/', include('informer.urls', namespace='informer')),
    #path('seva_api/seva_admin/', admin.site.urls)
]

#print(urlpatterns)

#print("admin",admin.site.urls)

sos_seva/signup/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.user_login, name='role_login'),
    path('authenticateUser', views.authenticateUser, name='authenticateUser'),
    path('logout', views.user_logout, name='user_logout'),
    path('register',views.register,name='register'),
    ]

app_name = 'signup'

sos_seva/isb_db/models.py
from django.db import models
from django.utils import timezone


class Verified_data(models.Model):
    name = models.CharField(null=True, max_length= 255, verbose_name="Organization Name")
    poc = models.CharField(null=True, max_length=255, verbose_name="Point of Contact")
    phone = models.CharField(null=True, max_length=255, verbose_name="Phone")
    address = models.CharField(null=True, max_length=255, verbose_name="Address", )
    pincode = models.CharField(null=True, max_length=20, verbose_name="Pincode")
    notes = models.TextField(null=True, verbose_name="Notes")
    email = models.CharField(null=True, max_length=255, verbose_name="Email")
    verified_status = models.CharField(max_length=20 ,default='N', verbose_name="Status")
    verified_date = models.DateTimeField(default=timezone.now, null=True, verbose_name="Verfied Date")
    verified_by = models.CharField(null=True, max_length=255, verbose_name="Verified By")
    city = models.CharField(max_length=100, verbose_name="City")
    category = models.CharField(max_length=100, verbose_name="Category")

    class Meta:
        db_table = "isb_data"

sos_seva/isb_db/views.py
from django.shortcuts import render, redirect
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone, dateformat
from django.http import HttpResponse, JsonResponse
from .models import Verified_data
from datetime import datetime


# Create your views here.
def dashboard(request):
    city = [item['city'] for item in Verified_data.objects.order_by().values('city').distinct()]
    category = [item['category'] for item in Verified_data.objects.order_by().values('category').distinct()]
    if request.session.has_key('is_logged'):
        return render(request, 'report.html', {"cities": city, "categories": category})
    else:
        if request.user.is_authenticated:
            request.session['is_logged'] = True
            request.session['username'] = request.user.username
            request.session['first_name'] = request.user.first_name
            request.session['last_name'] = request.user.last_name
            return render(request, 'report.html', {"cities": city, "categories": category})
        else:
            return render(request, 'login.html')
        # return render(request, 'login.html')


class information_ret(BaseDatatableView):
    # The model we're going to show
    model = Verified_data

    # define the columns that will be returned

    # columns = ['name', 'poc', 'phone', 'address', 'email', 'notes', 'verified_status', 'verified_date', 'verified_by' , 'city', 'category']
    columns = ['name', 'poc', 'phone', 'address', 'pincode' ,'email', 'notes', 'verified_status', 'verified_date', 'verified_by',
               'Edit']

    # define column names that will be used in sorting
    # order is important and should be same as order of columns
    # displayed by datatables. For non sortable columns use empty
    # value like ''
    # order_columns = ['id']

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 50

    # TODO: Fix time going to column
    def render_column(self, row, column):
        if column == 'Edit':
            return """<button class='btn btn-primary' style="cursor:pointer;" data-toggle="modal" data-target="#info_modal" onclick="show_modal({})">View</button>""".format(
                row.id)
        if column == 'verified_date':
            # import pdb
            # pdb.set_trace()
            if row.verified_date: 
                return timezone.localtime(row.verified_date).strftime("%d %b, %H:%M")
                # return row.verified_date.strftime("%d %b, %H:%M")
        return super(information_ret, self).render_column(row, column)

    # TODO: Change istartswiths to icontains
    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(name__icontains=search) |
                           Q(poc__icontains=search) |
                           Q(phone__icontains=search) | Q(email__icontains=search) |
                           Q(notes__icontains=search) | Q(address__icontains=search) |
                           Q(pincode__icontains=search))

        # more advanced example using extra parameters
        city_opt = self.request.GET.get('city', None)
        category_opt = self.request.GET.get('category', None)

        if city_opt and category_opt:
            qs = qs.filter(Q(city=city_opt) & Q(category=category_opt))
        # print("In t")
        # import pdb
        # pdb.set_trace()
        print(len(qs))
        print(qs)
        print(type(qs))
        # import pdb; pdb.set_trace()
        return qs


@csrf_exempt
def get_details(request):
    resource_details = {}
    id = request.POST.get('pk', None)

    if id:
        resource_obj = Verified_data.objects.get(id=id)
        if resource_obj:
            if resource_obj.verified_date == None:
                verified_date = ''
            else:
                verified_date = timezone.localtime(resource_obj.verified_date).strftime("%d %b, %H:%M")

            resource_details = {
                "name": resource_obj.name.capitalize(),
                "poc": resource_obj.poc,
                "phone": resource_obj.phone,
                "email": resource_obj.email,
                "notes": resource_obj.notes,
                "status": resource_obj.verified_status,
                'verified_date': verified_date,
                'verified_by': resource_obj.verified_by,
                'address': resource_obj.address,
                'pincode': resource_obj.pincode
            }

    print(resource_details)
    return JsonResponse({'resource_details': resource_details}, safe=False)


@csrf_exempt
def update_database(request):
    msg = "Failed to update!"
    response = {}
    id = request.POST.get('pk', None)

    if id:
        user = request.POST.get('user', None)
        name = request.POST.get('name', None)
        poc = request.POST.get('poc', None)
        phone = request.POST.get('phone', None)
        email = request.POST.get('email', None)
        notes = request.POST.get('notes', None)
        status = request.POST.get('status', None)
        pincode = request.POST.get('pincode', None)
        address = request.POST.get('address', None)

        try:
            update_obj = Verified_data.objects.filter(id=id)
            update_obj.update(
                name=name,
                poc=poc,
                phone=phone,
                email=email,
                notes=notes,
                address=address,
                pincode=pincode,
                verified_status=status,
                verified_date=timezone.now(),
                verified_by=user,
            )
            msg = "Updated!"
        except:
            msg = "Update Failed!"

    return JsonResponse({"result": msg}, safe=False)


@csrf_exempt
def new_resource(request):
    msg = "Failed to create!"
    response = {}
    user = request.POST.get('user', None)

    if user:
        name = request.POST.get('name', None)
        poc = request.POST.get('poc', None)
        phone = request.POST.get('phone', None)
        email = request.POST.get('email', None)
        notes = request.POST.get('notes', None)
        status = request.POST.get('status', None)
        city = request.POST.get('city', None)
        category = request.POST.get('category', None)
        pincode = request.POST.get('pincode', None)
        address = request.POST.get('address', None)

        try:
            new_obj = Verified_data.objects.create(
                name=name,
                poc=poc,
                phone=phone,
                email=email,
                notes=notes,
                verified_status=status,
                verified_date=timezone.now(),
                verified_by=user,
                city=city,
                category=category,
                address=address,
                pincode=pincode
            )
            msg = "Created Entry!!"
        except:
            msg = "Insertion Failed!"

    return JsonResponse({"result": msg}, safe=False)

sos_seva/isb_db/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Twitter and ISB DB</title>
<link rel="shortcut icon" href="{% static 'images/fav.ico' %}">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <script src="{% static 'js/jquery3_6.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/datatables.css' %}">
  <script src="{% static 'js/datatables.js' %}"></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="" class="nav-link">Home</a>
      </li>
    </ul>
<ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
    {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link"  href="{% url 'signup:user_logout' %}" role="button">
          <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
        </a>
      </li>
    {% endif %}
  </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'images/logo.png' %}" alt="Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Twitter and ISB DB</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
<!--        <div class="image">-->
<!--          <img src="{% static 'dist/img/avatar.png' %}" class="img-circle elevation-2" alt="User Image">-->
<!--        </div>-->
        <div class="info">

          <a href="#" class="d-block" title="" >
            {% if request.session.first_name %}
            {{ request.session.first_name}}
            {{ request.session.last_name}}
            {% else %}
            {{ request.session.username}}
            {% endif %}
        </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item selected">
            <a href="{% url 'isb_db:dashboard' %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
        </ul>

        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item selected">
            <a href="{% url 'informer:index' %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Twitter
              </p>
            </a>
          </li>
        </ul>

      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">


    <!-- Main content -->
      {% block content %}
      {% endblock %}
    <!-- /.content -->

  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
<!--  <footer class="main-footer">-->
<!--    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>-->
<!--    All rights reserved.-->
<!--    <div class="float-right d-none d-sm-inline-block">-->
<!--      <b>Version</b> 3.0.5-->
<!--    </div>-->
<!--  </footer>-->
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<!--<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>-->
<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<!--<script src="{% static 'plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>-->
<script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
<script src="{% static 'plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
<script src="{% static 'plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>
<!-- ChartJS -->
<!--<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>-->

<!-- PAGE SCRIPTS -->
<!--<script src="{% static 'dist/js/pages/dashboard2.js' %}"></script>-->

</body>
</html>

sos_seva/isb_db/templates/report.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Report</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="">Home</a></li>
                    <li class="breadcrumb-item active">Data Source</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">

            <div class="clearfix hidden-md-up"></div>

        </div>

        <!-- Main row -->

        <div class="row">
            <div class="col-md-12">
                <!-- OPTIONS DROPDOWN -->
                <div class="card">
                    <div class="card-header border-transparent">
                        <h3 class="card-title">Options</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="table_options form-inline">
                            <div class="form-group mb-2 col-md-4">
                                <label for="city_selector">City</label> &nbsp;&nbsp;&nbsp;
                                <select id="city_selector" class="form-select" onchange="getSelectValue();">
                                    {% for city in cities %}
                                    <option value="{{city}}">{{city}}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group mb-2 col-md-4">
                                <label for="category_selector">Category</label> &nbsp;&nbsp;&nbsp;
                                <select id="category_selector" class="form-select" onchange="getSelectValue();">
                                    {% for category in categories %}
                                    <option value="{{category}}">{{category}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            
                            <div class="form-group mb-2 col-md-2">
                                <button class="btn btn-block btn-primary"  style="cursor:pointer;" data-toggle="modal" data-target="#info_new_modal">Create New</button>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>


        <div class="row">
            <div class="col-md-12">
                <!-- TABLE: LATEST ORDERS -->
                <div class="card">
                    <div class="card-header border-transparent">
                        <h3 class="card-title">Information</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table id="info_from_db" class="dataTable" style="width: 100%;" role="grid">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>PoC</th>
                                    <th>Phone</th>
                                    <th>Address</th>
                                    <th>Pincode</th>
                                    <th>Email</th>
                                    <th>Notes</th>
                                    <th>Verification Status</th>
                                    <th>Verified Date</th>
                                    <th>Verified By</th>
<!--                                    <th>City</th>-->
<!--                                    <th>Category</th>-->
                                    <th>View</th>
                                </tr>
                                </thead>
                            </table>

                        </div>
                        <!-- /.table-responsive -->
                    </div>

                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!--/. container-fluid -->


    <!-- Modal -->
    <div class="modal fade bd-example-modal-lg" id="info_modal" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">View</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    {% include "resource_details.html" %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>


    <!-- Modal New Entry-->
    <div class="modal fade bd-example-modal-lg" id="info_new_modal" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">New Entry</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    {% include "new_resource.html" %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

    <footer style="padding: 20px">
        Data Sourced from : ISB
    </footer>
</section>
<!-- /.content -->


<script>
    var init_flag = false;

    $(document).ready(function () {
        console.log("ready")
        // load_dataTable()
        $('#info_modal').find('form').trigger('reset');
    })

    function reloadPage(){
        window.location = window.location
    }

    function load_dataTable() {         // Function to load data table
        
        var city = $('#city_selector option:selected').val();
        var category = $('#category_selector option:selected').val();
        console.log(init_flag)

        console.log(city)
        console.log(category)
        var oTable = $('#info_from_db').dataTable({
            orderCellsTop: true,
            pageLength: 50,
            processing: true,
            serverSide: true,
            bSort: false,
            "ajax": {
                    "url": "{% url 'isb_db:info_ret' %}",
                    "type": "GET",
                    "data": {'city': city, 'category': category}
                }
        });
        console.log("{% url 'isb_db:info_ret' %}")
    }

    $('#city_selector').on('change', function(){
        reloadPage()
    });

    $('#category_selector').on('change', function(){
        reloadPage()
    });


    window.addEventListener('load', function(){         // state retention of city
    if (localStorage.city) {
        var sel = document.querySelector('#city_selector');
        sel.value = localStorage.city;
        }
    if (localStorage.category) {                        // state retention of category
        var sel = document.querySelector('#category_selector');
        sel.value = localStorage.category;
        }
    load_dataTable()

    });

    function getSelectValue(){
    var city = document.querySelector('#city_selector');
    localStorage.city = city.value;

    var category = document.querySelector('#category_selector');
    localStorage.category = category.value;

    location.reload();
}

var modal_id;

function show_modal(id)             // show edit modal
{
    modal_id = id;
    // console.log("Modal ID is" + modal_id);
    $('.tabs-container').css('opacity','0.4');
    $('#loading').show();
//    $("#passes_page").hide();
            $.ajax({
                url: "{% url 'isb_db:get_details' %}",
                data: {'pk':id},
                type: 'POST',
                success: function(result){
                    $('#loading').hide();
                    // console.log(result);
                    $('.tabs-container').css('opacity','1');
                    //console.log(result);
                    $("#pk").val(modal_id);
                    $("#name").val(result['resource_details'].name);
                    $("#poc").val(result['resource_details'].poc);
                    $("#phone").val(result['resource_details'].phone);
                    $("#email").val(result['resource_details'].email);
                    $("#notes").val(result['resource_details'].notes);
                    $("#address").val(result['resource_details'].address);
                    $("#pincode").val(result['resource_details'].pincode);
                    if (result['resource_details'].status == 'Y'){
                        // $("#status_y").checked=true;
                        $("#status_y").prop("checked", true);
                    }
                    else if (result['resource_details'].status == 'N'){
                        // $("#status_n").checked=true;
                        $("#status_n").prop("checked", true)
                    }

                    // $("#status").val(result['resource_details'].status);
                    $("#verified_date").val(result['resource_details'].verified_date);
                    $("#verified_by").val(result['resource_details'].verified_by);

                },
                    error:function(err){
                        Alert("Error",err.statusText);

                }
        });
}
//
$('#info_modal').on('hidden.bs.modal', function () {
    // $(this).find('form').trigger('reset');
    $("#status_y").prop("checked", false);
    $("#status_n").prop("checked", false);

})

function update_resource(){             // function to update resource value to DB

    var pk =  $('#pk').val();
    var user = $('#user').val();
    var name = $('#name').val();
    var poc = $('#poc').val();
    var phone = $('#phone').val();
    var email = $('#email').val();
    var notes = $('#notes').val();
    var status = $("input[name='status']:checked").val();
    // var verified_data = $('#verified_data').val();
    // var verified_by = $('#verified_by').val();
    var address = $('#address').val();
    var pincode = $('#pincode').val();

    var data = {
        "pk": pk,
        "user": user,
        "name": name,
        "poc": poc,
        "phone": phone,
        "email": email,
        "notes": notes,
        "status": status,
        "address":address,
        "pincode": pincode
    }

    console.log(data)

    $.ajax({
        url: "{% url 'isb_db:update_info' %}",
        type:'POST',
        data: data,
        success: function(result){
            // alert("Data Updated!")
            alert(result['result'])
            reloadPage()
        },
        error: function(error){
            Alert("Error",error.statusText);
        }
    });
}


function new_resource(){             // function to create new resource value to DB

var user = $('#user').val();
var name = $('#new_name').val();
var poc = $('#new_poc').val();
var phone = $('#new_phone').val();
var email = $('#new_email').val();
var notes = $('#new_notes').val();
var status = $("input[name='new_status']:checked").val();
var new_city = $('#new_city').val();
var new_category = $('#category_new').val();
var address = $('#new_address').val();
var pincode = $('#new_pincode').val();

var data = {
    "user": user,
    "name": name,
    "poc": poc,
    "phone": phone,
    "email": email,
    "notes": notes,
    "status": status,
    "city": new_city,
    "category": new_category,
    "address": address,
    "pincode": pincode
}

console.log(data)

$.ajax({
    url: "{% url 'isb_db:new_resource' %}",
    type:'POST',
    data: data,
    success: function(result){
        // alert("Data Updated!")
        alert(result['result'])
        reloadPage()
    },
    error: function(error){
        Alert("Error",error.statusText);
    }
});
}


$('#info_new_modal').on('hidden.bs.modal', function () {
    // $(this).find('form').trigger('reset');
    $("#new_status_y").prop("checked", false);
    $("#new_status_n").prop("checked", false);

})

</script>


{% endblock %}